name: Buildcounter
 
on: push
 
env:
  TOKEN: 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 

  #BUILD_COUNTER_REPO: venkatsagiraju/Buildcounter
  #BUILD_COUNTER_BRANCH: Init
  #BUILD_COUNTER_FILE: counter.txt
  #VERSION: 2022.4.3
 
jobs:
  my_job:
    runs-on: windows-latest
    steps:
 
      - name: Clone build counter repo
        uses: actions/checkout@v2
        with:
          repository: venkatsagiraju/Buildcounter
          ref: Init
      - name: Read file
        run: |
          cat counter.txt
     
