name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Generate build number
      run: |
        $major = "2022"
        $minor = "99"
        $patch = "99"
        $version = "$major.$minor.$patch"
        Write-Host "VERSION=$version" > version.txt
    
  downstream:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Trigger Workflow and Wait
      run: |
        curl -X POST \
          -H "Authorization: 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}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/venkatsagiraju/Buildcounter/actions/workflows/build2.yml/dispatches" \
          -d '{"ref":"main"}'
        sleep 10s
    - name: Deploy Web App
      run: |
        echo "Deploy Web App"
        sleep 10s

 

  my_job:
    needs: downstream
    runs-on: windows-latest
    steps:
    - name: Clone build counter repo
      uses: actions/checkout@v2
      with:
        repository: venkatsagiraju/Buildcounter
        ref: main
    - name: Read file
      run: |
        cat counter.txt
