name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Generate build number
      run: |
        $major = "2022"
        $minor = "99"
        $patch = "99"
        $version = "$major.$minor.$patch"
        Write-Host "VERSION=$version" > version.txt
    
  downstream:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Build Web App 
      run: |
        echo "Build Web App test"
        sleep 10s
    - uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
       owner: venkatsagiraju
       repo: Buildcounter
       github_token: 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
       workflow_file_name: build2.yml 
       ref: main
    - name: Deploy Web App
      run: |
        echo "Deploy Web App"
        sleep 10s 
 

  my_job:
    needs: downstream
    runs-on: windows-latest
    steps:
    - name: Clone build counter repo
      uses: actions/checkout@v2
      with:
        repository: venkatsagiraju/Buildcounter
        ref: main
    - name: Read file
      run: |
        cat counter.txt
