name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Generate build number
      run: |
        $major = "2022"
        $minor = "99"
        $patch = "9"
        $version = "$major.$minor.$patch"
        Write-Host "VERSION=$version" > version.txt
